def readpom;
node{
    stage('SCM Checkout'){
        
        git 'https://gitlab.training.dagility.com/manojkumar_gnanasekaran/dagilitytrainingassignmentmavenfreestyle.git'
    }
    stage('read POM'){
        readpom = readFile 'mavenworkspace/HelloWorld/pom.xml';
        dev artifactversion = readpom.version;
        echo "The version of artifact is - ${artifactversion}"
    }
    stage('Compile-Package'){
        //Get maven home path
        def mvnHome = tool name: 'maven', type: 'maven'
        sh "${mvnHome}/bin/mvn package"
    }
}
