def readpom;
node{
    stage('SCM Checkout'){
        
        git 'https://gitlab.training.dagility.com/manojkumar_gnanasekaran/dagilitytrainingassignmentmavenfreestyle.git'
    }
    stage('read POM'){
        readpom = readFile 'mavenworkspace/HelloWorld/pom.xml';
        //dev artefactversion = readpom.version;
        //echo "The version of artifact is - ${artefactversion}"
    }
    stage('Compile-Package'){
        //Get maven home path
        sh 'mvn archetype:generate -B ' +
      '-DarchetypeGroupId=org.apache.maven.archetypes ' +
      '-DarchetypeArtifactId=maven-archetype-quickstart ' +
      '-DgroupId=com.trainingMaven -DartifactId=HelloWorld'
        def mavenHome = tool name: 'maven', type: 'maven'
        sh "${mavenHome}/bin/mvn package"
    }
}
